---
- name: Configure SonarQube
  hosts: localhost

  tasks:
### Этот блок выводит внутренний ip-адрес субд полученный в outputs от terraform
    - name: Get DB private IP-addr
      command: "terraform output -raw db_private_ip"
      register: db_private_ip

    - name: Add vars in main.yml
      lineinfile:
        path: "{{ playbook_dir }}/../roles/sonar-role/vars/main.yml"
        line: "db_private_ip: \"{{ db_private_ip.stdout }}\""
        state: present
        insertafter: EOF
######

- name: Install postres
  hosts: postgres
  become: true
  roles:
    - postgres-role

- name: Install nexus
  hosts: nexus
  become: true
  roles:
    - nexus-role

- name: Install sonar
  hosts: sonar
  become: true
  roles:
    - sonar-role
